name: App on ec2
on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: checout repo
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean package
      

  # deploy:
  #   name: Deploy to EC2 on master branch push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout the files
  #       uses: actions/checkout@v2

  #     - name: Deploy to Server 1
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  #         REMOTE_HOST: ${{ secrets.HOST_DNS }}
  #         REMOTE_USER: ${{ secrets.USERNAME }}
  #         TARGET: ${{ secrets.TARGET_DIR }}
